version: "3.9"

services:
  executor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: executor-container
    environment:
      # Load sensitive variables from .env file
      PRIVATE_KEY_LOCAL: "${PRIVATE_KEY_LOCAL}" 

      # Node environment
      NODE_ENV: "testnet"

      # Logging settings
      LOG_LEVEL: "debug"
      LOG_PRETTY: "false"

      # Process orders and claims
      EXECUTOR_PROCESS_ORDERS: "true"
      EXECUTOR_PROCESS_CLAIMS: "true"

      # Limit on gas usage
      EXECUTOR_MAX_L3_GAS_PRICE: "8"

      # Networks & RPC endpoints
      ENABLED_NETWORKS: "base-sepolia,optimism-sepolia,l1rn"
      # Orders processing via API
      EXECUTOR_PROCESS_PENDING_ORDERS_FROM_API: "false"

      # Batch bidding
      EXECUTOR_ENABLE_BATCH_BIDDING: "true"

      # Enable bidding
      EXECUTOR_PROCESS_BIDS_ENABLED: "true"
    volumes:
      - .:/app
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
